services:
  frontend:
    container_name: mira-frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/vue-app
      - /vue-app/node_modules

  backend:
    container_name: mira-backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/express-app
      - /express-app/node_modules
